### ISSUE TITLE
mise à jour 2024 ?

### ISSUE THREAD

**Issue by AmauryVanEspen** [AntoineViau/eurl-sasu#58]
Bonjour @guillaume-sainthillier 
le nouveau repo est il maintenu pour 2024 ou adaptable ?
j'aime vraiment la présentation concise et simple ainsi que le partage d'URL avec les parametres
Merci
Cordialement
Amaury

**Comment by AntoineViau** [comment]
Bonjour,
Vous avez envoyé votre message sur le repo d'origine qui n'est plus maintenu.
Désormais tout se passe ici : https://github.com/guillaume-sainthillier/eurl-sasu

**Comment by AmauryVanEspen** [comment]
Bonjour @AntoineViau 
je comprends, cependant il n'est pas possible d'ouvrir d'issue sur le nouveau repo

**Comment by guillaume-sainthillier** [comment]
Hello @AmauryVanEspen, le repo a été mis à jour pour accepter les issues.
En revanche, le moteur n'est pas mis à jour depuis de nombreuses années, n'hésite pas à proposer une PR avec les nouveaux paramètres si besoin.

Pour info tu as aussi pas mal de simulateurs open source ici : https://mon-entreprise.urssaf.fr/
